version: '3.8'

services:
  frontend:
    build: .
    container_name: thesis-frontend
    ports:
      - "80:80"
    networks:
      - thesis-network

networks:
  thesis-network:
    driver: bridge
    external: true